import { Agency, Brand, Report, VisibilitySummary, Competitor, Mention, AIQuery, PlatformStatus as PlatformStatusType } from "@/types";

export const mockAgency: Agency = {
 id: "agency-1",
 name: "Acme Digital Agency",
 email: "admin@acmeagency.com",
 plan: "growth",
 whiteLabelConfig: {
 logoUrl: "https://acme.com/logo.png",
 brandName: "Acme Monitor",
 primaryColor: "#8B5CF6",
 hidePoweredBy: true,
 },
 apiKey: "sk_live_abc123",
 emailVerified: true,
 brandsCount: 8,
 scansThisMonth: 847,
 createdAt: "2024-06-15T10:00:00Z",
 updatedAt: "2026-09-01T10:00:00Z",
};

export const mockBrands: Brand[] = [
 {
 id: "brand-1",
 agencyId: "agency-1",
 name: "BrandLens",
 industry: "MarTech / AI Analytics",
 description: "AI-powered brand visibility monitoring platform",
 websiteUrl: "https://brandlens.ai",
 keywords: [
 { term: "BrandLens", type: "brand", weight: 1.0 },
 { term: "BrandLens AI", type: "brand", weight: 0.9 },
 { term: "AI brand monitoring", type: "category", weight: 0.6 },
 { term: "AI visibility tool", type: "category", weight: 0.5 },
 ],
 competitors: [
 { name: "MentionStream", keywords: ["MentionStream", "MentionStream AI"] },
 { name: "BrandWatch AI", keywords: ["BrandWatch AI"] },
 ],
 scanFrequency: "daily",
 isActive: true,
 lastScannedAt: "2026-09-06T08:30:00Z",
 visibilityScore: 0.42,
 totalMentions: 89,
 createdAt: "2024-08-01T10:00:00Z",
 updatedAt: "2026-09-06T08:30:00Z",
 },
 {
 id: "brand-2",
 agencyId: "agency-1",
 name: "CloudSync Pro",
 industry: "SaaS / Cloud Infrastructure",
 description: "Enterprise cloud synchronization and backup platform",
 websiteUrl: "https://cloudsyncpro.com",
 keywords: [
 { term: "CloudSync Pro", type: "brand", weight: 1.0 },
 { term: "cloud backup enterprise", type: "category", weight: 0.7 },
 ],
 competitors: [
 { name: "Dropbox Business", keywords: ["Dropbox Business"] },
 { name: "Box", keywords: ["Box cloud"] },
 ],
 scanFrequency: "weekly",
 isActive: true,
 lastScannedAt: "2026-09-05T10:00:00Z",
 visibilityScore: 0.35,
 totalMentions: 56,
 createdAt: "2024-09-15T10:00:00Z",
 updatedAt: "2026-09-05T10:00:00Z",
 },
 {
 id: "brand-3",
 agencyId: "agency-1",
 name: "TechVault",
 industry: "Cybersecurity",
 description: "Zero-trust security platform for enterprises",
 websiteUrl: "https://techvault.io",
 keywords: [
 { term: "TechVault", type: "brand", weight: 1.0 },
 { term: "zero trust security", type: "category", weight: 0.8 },
 ],
 competitors: [
 { name: "Palo Alto", keywords: ["Palo Alto"] },
 ],
 scanFrequency: "daily",
 isActive: true,
 lastScannedAt: "2026-09-06T07:00:00Z",
 visibilityScore: 0.58,
 totalMentions: 124,
 createdAt: "2025-01-10T10:00:00Z",
 updatedAt: "2026-09-06T07:00:00Z",
 },
];

export const mockReports: Report[] = [
 {
 id: "report-1",
 brandId: "brand-1",
 reportType: "weekly",
 periodStart: "2026-08-31",
 periodEnd: "2026-09-06",
 data: {
 summary: "BrandLens visibility improved 12% this week across ChatGPT and Perplexity.",
 totalQueries: 12,
 totalMentions: 8,
 visibilityScore: 0.42,
 sentimentDistribution: { positive: 4, neutral: 3, negative: 1 },
 },
 pdfUrl: "https://s3.brandlens.ai/reports/report-1/weekly.pdf",
 htmlUrl: "https://s3.brandlens.ai/reports/report-1/weekly.html",
 status: "completed",
 sentAt: "2026-09-06T09:00:00Z",
 sentTo: ["client@example.com"],
 createdAt: "2026-09-06T08:00:00Z",
 updatedAt: "2026-09-06T09:00:00Z",
 },
 {
 id: "report-2",
 brandId: "brand-1",
 reportType: "monthly",
 periodStart: "2026-08-01",
 periodEnd: "2026-08-31",
 data: {
 summary: "Monthly analysis shows consistent growth in AI visibility across all tracked platforms.",
 totalQueries: 48,
 totalMentions: 32,
 visibilityScore: 0.45,
 sentimentDistribution: { positive: 18, neutral: 10, negative: 4 },
 },
 pdfUrl: "https://s3.brandlens.ai/reports/report-2/monthly.pdf",
 status: "completed",
 sentAt: "2026-09-01T09:00:00Z",
 sentTo: ["client@example.com", "team@acme.com"],
 createdAt: "2026-09-01T08:00:00Z",
 updatedAt: "2026-09-01T09:00:00Z",
 },
 {
 id: "report-3",
 brandId: "brand-2",
 reportType: "weekly",
 periodStart: "2026-08-31",
 periodEnd: "2026-09-06",
 data: {
 summary: "CloudSync Pro maintains steady visibility in enterprise cloud backup category.",
 totalQueries: 8,
 totalMentions: 5,
 visibilityScore: 0.35,
 sentimentDistribution: { positive: 3, neutral: 2, negative: 0 },
 },
 pdfUrl: undefined,
 status: "generating",
 sentTo: [],
 createdAt: "2026-09-06T10:00:00Z",
 updatedAt: "2026-09-06T10:00:00Z",
 },
];

export const mockVisibilityData: VisibilitySummary[] = [
 {
 brandId: "brand-1",
 brandName: "BrandLens",
 agencyId: "agency-1",
 totalQueries: 142,
 totalMentions: 89,
 brandMentions: 72,
 competitorMentions: 17,
 visibilityScore: 0.42,
 avgBrandSentiment: 0.61,
 lastScanAt: "2026-09-06T08:30:00Z",
 platformsTracked: 4,
 },
 {
 brandId: "brand-2",
 brandName: "CloudSync Pro",
 agencyId: "agency-1",
 totalQueries: 98,
 totalMentions: 56,
 brandMentions: 45,
 competitorMentions: 11,
 visibilityScore: 0.35,
 avgBrandSentiment: 0.55,
 lastScanAt: "2026-09-05T10:00:00Z",
 platformsTracked: 3,
 },
];

export const mockCompetitors: Competitor[] = [
 {
 id: "comp-1",
 brandId: "brand-1",
 competitorName: "MentionStream",
 mentionCount: 42,
 visibilityScore: 0.50,
 avgSentimentScore: 0.0,
 lastMentionedAt: "2026-09-06T08:30:00Z",
 createdAt: "2024-08-01T10:00:00Z",
 updatedAt: "2026-09-06T08:30:00Z",
 },
 {
 id: "comp-2",
 brandId: "brand-1",
 competitorName: "BrandWatch AI",
 mentionCount: 72,
 visibilityScore: 0.35,
 avgSentimentScore: 0.12,
 lastMentionedAt: "2026-09-06T08:30:00Z",
 createdAt: "2024-08-01T10:00:00Z",
 updatedAt: "2026-09-06T08:30:00Z",
 },
];

export const mockMentions: Mention[] = [
 {
 id: "mention-1",
 brandId: "brand-1",
 queryId: "query-1",
 platform: "chatgpt",
 entityName: "BrandLens",
 entityType: "brand",
 context: "BrandLens is a strong contender for real-time AI visibility tracking across multiple platforms.",
 sentiment: "positive",
 sentimentScore: 0.65,
 confidenceScore: 0.88,
 position: 3,
 citationUrls: ["https://example.com/1"],
 createdAt: "2026-09-06T08:30:00Z",
 },
 {
 id: "mention-2",
 brandId: "brand-1",
 queryId: "query-2",
 platform: "perplexity",
 entityName: "BrandLens",
 entityType: "brand",
 context: "BrandLens provides real-time cross-platform AI monitoring with sentiment analysis.",
 sentiment: "positive",
 sentimentScore: 0.72,
 confidenceScore: 0.91,
 position: 2,
 citationUrls: [],
 createdAt: "2026-09-06T07:15:00Z",
 },
 {
 id: "mention-3",
 brandId: "brand-1",
 queryId: "query-3",
 platform: "claude",
 entityName: "MentionStream",
 entityType: "competitor",
 context: "MentionStream is known for its historical data depth and media monitoring.",
 sentiment: "neutral",
 sentimentScore: 0.0,
 confidenceScore: 0.80,
 position: 2,
 citationUrls: [],
 createdAt: "2026-09-06T06:00:00Z",
 },
];

export const mockQueries: AIQuery[] = [
 {
 id: "query-1",
 brandId: "brand-1",
 platform: "chatgpt",
 queryText: "What are the best AI tools for brand visibility monitoring?",
 queryVariant: "original",
 aiResponse: {
 rawText: "Here are the top AI tools for brand visibility monitoring... BrandLens is a strong contender...",
 model: "gpt-4-turbo",
 tokensUsed: 1250,
 latencyMs: 3400,
 citations: ["https://example.com/1"],
 },
 mentions: [
 { entity: "BrandLens", type: "brand", context: "BrandLens is a strong contender for real-time AI visibility tracking...", position: 3 },
 { entity: "BrandWatch AI", type: "competitor", context: "BrandWatch AI offers comprehensive social listening...", position: 1 },
 ],
 mentionCount: 2,
 sentimentScore: 0.65,
 confidenceScore: 0.88,
 status: "completed",
 responseTimeMs: 3400,
 createdAt: "2026-09-06T08:30:00Z",
 },
 {
 id: "query-2",
 brandId: "brand-1",
 platform: "perplexity",
 queryText: "Top AI-powered brand monitoring platforms in 2025",
 queryVariant: "paraphrased",
 aiResponse: {
 rawText: "Based on current market data, the top platforms include BrandLens for real-time cross-platform monitoring...",
 model: "sonar-large",
 tokensUsed: 980,
 latencyMs: 2100,
 citations: ["https://example.com/2", "https://example.com/3"],
 },
 mentions: [
 { entity: "BrandLens", type: "brand", context: "BrandLens provides real-time cross-platform AI monitoring...", position: 2 },
 ],
 mentionCount: 1,
 sentimentScore: 0.72,
 confidenceScore: 0.91,
 status: "completed",
 responseTimeMs: 2100,
 createdAt: "2026-09-06T07:15:00Z",
 },
];

export const mockPlatformStatus: PlatformStatusType[] = [
 {
 platform: "chatgpt",
 status: "operational",
 latencyMs: 2100,
 lastChecked: "2026-09-06T08:00:00Z",
 rateLimits: { requestsPerMinute: 3500, tokensPerMinute: 150000 },
 },
 {
 platform: "perplexity",
 status: "operational",
 latencyMs: 1800,
 lastChecked: "2026-09-06T08:00:00Z",
 rateLimits: { requestsPerMinute: 2000, tokensPerMinute: 80000 },
 },
 {
 platform: "claude",
 status: "operational",
 latencyMs: 3200,
 lastChecked: "2026-09-06T08:00:00Z",
 rateLimits: { requestsPerMinute: 1000, tokensPerMinute: 50000 },
 },
 {
 platform: "gemini",
 status: "degraded",
 latencyMs: 4500,
 lastChecked: "2026-09-06T08:00:00Z",
 rateLimits: { requestsPerMinute: 500, tokensPerMinute: 30000 },
 },
];

export const mockSentimentTrends = [
 { date: "2026-08-31", positive: 3, neutral: 4, negative: 1, avgSentiment: 0.42, total: 8 },
 { date: "2026-09-01", positive: 5, neutral: 2, negative: 1, avgSentiment: 0.58, total: 8 },
 { date: "2026-09-02", positive: 4, neutral: 3, negative: 0, avgSentiment: 0.67, total: 7 },
 { date: "2026-09-03", positive: 6, neutral: 1, negative: 2, avgSentiment: 0.50, total: 9 },
 { date: "2026-09-04", positive: 3, neutral: 5, negative: 1, avgSentiment: 0.38, total: 9 },
 { date: "2026-09-05", positive: 7, neutral: 2, negative: 0, avgSentiment: 0.78, total: 9 },
 { date: "2026-09-06", positive: 4, neutral: 3, negative: 1, avgSentiment: 0.52, total: 8 },
];

export const mockAnalytics = {
 brandId: "brand-1",
 period: { from: "2026-08-01", to: "2026-09-06" },
 summary: {
 totalQueries: 142,
 totalMentions: 89,
 visibilityScore: 0.42,
 avgSentiment: 0.61,
 platformsTracked: 4,
 },
 trends: [
 { date: "2026-08-01", queries: 12, mentions: 7, visibility: 0.38 },
 { date: "2026-08-05", queries: 12, mentions: 9, visibility: 0.45 },
 { date: "2026-08-10", queries: 12, mentions: 8, visibility: 0.42 },
 { date: "2026-08-15", queries: 12, mentions: 10, visibility: 0.48 },
 { date: "2026-08-20", queries: 12, mentions: 7, visibility: 0.40 },
 { date: "2026-08-25", queries: 12, mentions: 9, visibility: 0.44 },
 { date: "2026-09-01", queries: 12, mentions: 11, visibility: 0.50 },
 ],
 sentimentDistribution: { positive: 34, neutral: 41, negative: 14 } as Record<string, number>,
 platformBreakdown: [
 { platform: "chatgpt", queries: 42, mentions: 28, visibility: 0.45, avgSentiment: 0.62 },
 { platform: "perplexity", queries: 38, mentions: 22, visibility: 0.39, avgSentiment: 0.58 },
 { platform: "claude", queries: 35, mentions: 20, visibility: 0.42, avgSentiment: 0.55 },
 { platform: "gemini", queries: 27, mentions: 19, visibility: 0.38, avgSentiment: 0.48 },
 ],
 topQueries: [
 { queryText: "best AI brand monitoring tools", platform: "chatgpt", mentionCount: 3, avgSentiment: 0.70 },
 { queryText: "AI visibility tracking platforms", platform: "perplexity", mentionCount: 2, avgSentiment: 0.65 },
 ],
 keywordPerformance: [
 { term: "BrandLens", mentions: 45, avgPosition: 2.3 },
 { term: "AI brand monitoring", mentions: 12, avgPosition: 4.1 },
 { term: "AI visibility tool", mentions: 8, avgPosition: 5.2 },
 ],
};
